"""Universe of tradeable symbols. Hardcoded — fundingIntervalHours not available via API."""

UNIVERSE_8H: list[str] = [
    "1INCHUSDT", "AAVEUSDT", "ACHUSDT", "ADAUSDT", "ALGOUSDT",
    "APEUSDT", "APTUSDT", "ARBUSDT", "ARPAUSDT", "ARUSDT",
    "ASTRUSDT", "ATOMUSDT", "AVAXUSDT", "BANDUSDT", "BATUSDT",
    "BCHUSDT", "BELUSDT", "BNBUSDT", "BTCUSDT", "C98USDT",
    "CELOUSDT", "CELRUSDT", "CFXUSDT", "CHRUSDT", "CHZUSDT",
    "CKBUSDT", "COMPUSDT", "COTIUSDT", "CRVUSDT", "CTSIUSDT",
    "DASHUSDT", "DOGEUSDT", "DOTUSDT", "DYDXUSDT", "EDUUSDT",
    "EGLDUSDT", "ENSUSDT", "ETCUSDT", "ETHUSDT", "FETUSDT",
    "FILUSDT", "GALAUSDT", "GMXUSDT", "GRTUSDT", "GTCUSDT",
    "HBARUSDT", "HFTUSDT", "HIGHUSDT", "HOTUSDT", "ICPUSDT",
    "IDUSDT", "INJUSDT", "IOSTUSDT", "IOTAUSDT", "IOTXUSDT",
    "JASMYUSDT", "JOEUSDT", "KNCUSDT", "KSMUSDT", "LDOUSDT",
    "LINKUSDT", "LQTYUSDT", "LTCUSDT", "MANAUSDT", "MAVUSDT",
    "MINAUSDT", "MTLUSDT", "NEOUSDT", "ONEUSDT", "OPUSDT",
    "PEOPLEUSDT", "QNTUSDT", "QTUMUSDT", "RLCUSDT", "ROSEUSDT",
    "RSRUSDT", "RUNEUSDT", "SANDUSDT", "SFPUSDT", "SNXUSDT",
    "SOLUSDT", "SPELLUSDT", "SSVUSDT", "STGUSDT", "STXUSDT",
    "SUIUSDT", "SUSHIUSDT", "THETAUSDT", "TRXUSDT", "UNIUSDT",
    "USDCUSDT", "VETUSDT", "WOOUSDT", "XLMUSDT", "XRPUSDT",
    "XVGUSDT", "XVSUSDT", "YFIUSDT", "ZECUSDT", "ZENUSDT",
]
